# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-09 10:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SgFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qqnumber', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('flag', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
