# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgflag',
            name='flag',
            field=models.TextField(),
        ),
    ]
