# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0002_auto_20190109_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgflag',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
