# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-12-07 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 2, 22, 32, 105465, tzinfo=utc)),
        ),
    ]
